# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[(b'es', b'Espa\xc3\xb1ol'), (b'en', b'English')], default=b'es', max_length=2)),
                ('definition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to=b'images/')),
                ('pronunciation', models.FileField(blank=True, upload_to=b'pronunciations/')),
                ('is_formal', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='translation',
            name='translation',
            field=models.ManyToManyField(blank=True, related_name='word_translation', to='vocabulary_game.Word'),
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='word_category', to='vocabulary_game.Word'),
        ),
    ]
