# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to=b'images/')),
                ('pronunciation', models.FileField(blank=True, upload_to=b'pronunciations/')),
                ('is_honorific', models.BooleanField(default=False)),
                ('thl_phonetic_transcription', models.CharField(blank=True, help_text=b'THL Simplified Phonetic Transcription of Standard Tibetan', max_length=200)),
                ('thl_wylie_transliteration', models.CharField(blank=True, help_text=b'THL Extended Wylie Transliteration', max_length=200)),
                ('categories', models.ManyToManyField(blank=True, related_name='phrase_category', to='vocabulary_game.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.CharField(max_length=200)),
                ('language_code', models.CharField(choices=[(b'es', b'Espa\xc3\xb1ol'), (b'en', b'English')], default=b'es', max_length=2)),
                ('definition', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to=b'images/')),
                ('pronunciation', models.FileField(blank=True, upload_to=b'pronunciations/')),
                ('is_honorific', models.BooleanField(default=False)),
                ('thl_phonetic_transcription', models.CharField(blank=True, help_text=b'THL Simplified Phonetic Transcription of Standard Tibetan', max_length=200)),
                ('thl_wylie_transliteration', models.CharField(blank=True, help_text=b'THL Extended Wylie Transliteration', max_length=200)),
                ('grammar', models.CharField(blank=True, max_length=200)),
                ('categories', models.ManyToManyField(blank=True, related_name='word_category', to='vocabulary_game.Category')),
                ('phrase', models.ManyToManyField(blank=True, related_name='word_phrase', to='vocabulary_game.Phrase')),
                ('translation', models.ManyToManyField(blank=True, related_name='word_translation', to='vocabulary_game.Translation')),
            ],
        ),
        migrations.AddField(
            model_name='phrase',
            name='translation',
            field=models.ManyToManyField(blank=True, related_name='pharse_translation', to='vocabulary_game.Translation'),
        ),
    ]
