# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary_game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='phrase',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='translation',
            name='translation',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
