# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-24 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170311_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='language_code',
            field=models.CharField(choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=2),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='pronunciation',
            field=models.FileField(blank=True, upload_to='pronunciations/'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='language_code',
            field=models.CharField(choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=2),
        ),
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='word',
            name='pronunciation',
            field=models.FileField(blank=True, null=True, upload_to='pronunciations/'),
        ),
    ]
