# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170308_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'images/'),
        ),
    ]
