# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170311_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='grammar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='is_honorific',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='word',
            name='thl_phonetic_transcription',
            field=models.CharField(blank=True, help_text='THL Simplified Phonetic Transcription of Standard Tibetan', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='thl_wylie_transliteration',
            field=models.CharField(blank=True, help_text='THL Extended Wylie Transliteration', max_length=200, null=True),
        ),
    ]
